import {StyleSheet, Dimensions} from 'react-native';
import colors from '../../constants/colors';
import sizes from '../../constants/fontSize';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  boardUp: {
    height: '60%',
    backgroundColor: '#222',
  },
  boardDown: {
    height: '60%',
    backgroundColor: '#222',
  },
  listContainer: {
    backgroundColor: colors.LIST_BG_COLOR,
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  inputHeaderContainer: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    backgroundColor: colors.BRAIN_STORM_BOARD_BG,
    marginHorizontal: 16,
    borderRadius: 8,
  },
  inputHeader: {
    height: 50,
    width: width - 82,
    borderRadius: 8,
  },
  backgroundImage: {
    flex: 1,
    width: width - 32,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 25,
  },
  boardInput: {
    width: width - 32,
    fontFamily: 'Poppins-Regular',
    fontSize: sizes.listHeaderFontSize,
    paddingTop: -24,
    lineHeight: 30,
  },
  addHeader: {
    width: 50,
    height: 50,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 1,
  },
  brainStormText: {
    width: 150,
    height: 46,
    alignSelf: 'center',
    textAlign: 'center',
    color: colors.LAYER_COLOR,
    fontFamily: 'Poppins-Bold',
    textAlignVertical: 'center',
  },
  brainStormTextActive: {
    borderWidth: 1,
    borderRadius: 8,
    color: 'white',
    backgroundColor: colors.COMPLETED_COLOR,
    borderColor: colors.COMPLETED_COLOR_STROKE,
  },
  addTaskText: {
    fontFamily: 'Poppins-Bold',
    fontSize: sizes.normalFontSize,
  },
  inProgressContainer: {
    height: 370,
    width: '100%',
    paddingHorizontal: 16,
    paddingBottom: 50,
  },
  inProgressBodyContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.MEDIUM_COLOR,
    borderRadius: 10,
    padding: 16,
  },
  dueContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 10,
    height: 50,
    width: width - 164,
    paddingHorizontal: 10,
    fontFamily: 'Poppins-Regular',
  },
  dueTextContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    fontSize: sizes.normalFontSize,
  },
  dueButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    width: 100,
    justifyContent: 'space-between',
    paddingLeft: 10,
  },
  listTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: sizes.listHeaderFontSize,
    color: '#19191E',
  },
  createNewTask: {
    width: '100%',
    height: 50,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 20,
    backgroundColor: '#fff',
    marginTop: 10,
    borderRadius: 10,
  },
  activityIndicator: {
    position: 'absolute',
    backgroundColor: 'rgba(0,0,0,0.1)',
    width: width,
    height: height,
    zIndex: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    width: '70%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 15,
  },
  button: {
    width: '50%',
    height: 50,
    justifyContent: 'center',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    marginTop: 20,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    fontSize: sizes.listHeaderFontSize,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: sizes.listHeaderFontSize,
    fontFamily: 'Poppins-Regular',
  },
  modalInputText: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.LAYER_COLOR,
    height: 50,
    width: '100%',
    fontSize: sizes.listHeaderFontSize,
    fontFamily: 'Poppins-Regular',
    padding: 10,
  },
  error: {
    borderColor: 'red',
  },
});

export default styles;
