export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGINSUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTERSUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKSSUCCESS';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASKSUCCESS';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';
